#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later

{ [[ $(uname) == Darwin ]] || [[ $(uname) =~ .*BSD.* ]]; } && {
  alias sed="gsed"
  alias grep="ggrep"
  alias awk="gawk"
}

function check_deps() {
  echo -n "Pandoc: " && ( command -v pandoc || echo "Not found." )
  echo -n "pandoc-crossref: " && ( { command -v pandoc-crossref || ls ./pandoc-crossref; } || echo "Not found." )
  echo -n "Python: " && ( command -v python || echo "Not found." )
  echo -n "xmllint: " && ( command -v xmllint || echo "Not found." )
  echo -n "Perl: " && ( command -v perl || echo "Not found." )
  { [[ $(uname) == Darwin ]] || [[ $(uname) =~ .*BSD.* ]]; } && {
    echo -n "GNU awk: " && ( command -v gawk || echo "Not found." )
    echo -n "GNU grep: " && ( command -v ggrep || echo "Not found." )
    echo -n "GNU sed: " && ( command -v gsed || echo "Not found." )
  }
  echo -n "urlextract: " && ( command -v urlextract || echo "Not found." )
}

function update_xliff() {
  OUTPUT="$2"
  rm "$OUTPUT" 2> /dev/null
  # Read all tex files
  while read -r file; do
    # Title
    while read -r line_title; do
      title_key=$(echo "${line_title}" | grep -oP "(?<=\%\%##).*(?=>>)")
      nests=0
      while true; do
        title_value=$(echo "${line_title}" | grep -oP '((?<=section{)|(?<=subsection{)|(?<=subsubsection{)|(?<=chapter{)|(?<=caption{)|(?<=paragraph{))([^}]*}){'$nests'}[^}]*(?=})')
        open=$(echo "$title_value" | grep -o "{" | wc -l)
        close=$(echo "$title_value" | grep -o "}" | wc -l)
        [[ $open == "$close" ]] && break
        [[ $open -gt $close ]] && nests=$((nests + 1))
      done
      echo "<string name=\"${title_key}\"><![CDATA[${title_value}]]></string>" >> "${OUTPUT}"
    done < <(grep -P "(?<=\%\%##).*(?=>>)" "${file}" | sed -e 's/\\/\\\\/g')
    # Content
    while read -r content_key; do
      content_value=$(sed '1,/%%!!'"${content_key}"'<</d;/%%!!>>/,$d' "${file}")
      echo "<string name=\"${content_key}\"><![CDATA[${content_value}]]></string>" >> "${OUTPUT}"
    done < <(grep -oP "(?<=\%\%!!).*(?=<<)" "${file}")
  done < <(find ./ -type f -name "*.tex")
  # Write header
  sed -i -e '1i <?xml version="1.0" encoding="utf-8"?>' \
    -e '1i <!-- Generated by doctool.sh. DO NOT EDIT THIS FILE. -->' \
    -e '1i <resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">' \
    -e '$a </resources>' "${OUTPUT}"
}

function merge_translation() {
  INPUT="$2"
  OUTPUT_DIR="$3"
  keys=$(grep -oP "(?<=<string name=\").*?(?=\">)" "${INPUT}")

  find . | grep -e '\.tex$' -e '.png$' -e '.svg$' -e doctool.sh | rsync -R $(cat) "${OUTPUT_DIR}"

  while read -r key_content; do
    content_value=$(echo 'cat resources/string[@name="'${key_content}'"]/text()' | xmllint --shell "${INPUT}" | sed -e '$d' -e '1d' | sed -e 's/\\/\\\\/g' -e '1s/^<!\[CDATA\[//g' -e '$s/]]>$//g')
    file=$(grep -rl --include="*.tex" "\%\%!!${key_content}<<" "${OUTPUT_DIR}")
    source=$(cat "${file}")
    echo "import re;import sys;print(re.sub(r'(?<=%%!!"${key_content}"<<\n)[^%%!!>>]*(?=%%!!>>)', sys.argv[2]+'\n', sys.argv[1], flags=re.M))" | python - "${source}" "${content_value}" >"${file}"
  done < <(echo "$keys" | grep -Pv ".*(?===title)")

  while read -r key_title; do
    title_value=$(echo 'cat resources/string[@name="'${key_title}'"]/text()' | xmllint --shell "${INPUT}" | sed -e '$d' -e '1d' | sed -e 's/\\/\\\\/g' -e 's/\//\\\//g' -e '1s/^<!\[CDATA\[//g' -e '$s/]]>$//g')
    file=$(grep -rl --include="*.tex" "\%\%##${key_title}>>" "${OUTPUT_DIR}")
    nests=0
    while true; do
      chknests=$(grep -oP '((?<=section{)|(?<=subsection{)|(?<=subsubsection{)|(?<=chapter{)|(?<=caption{)|(?<=paragraph{))([^}]*}){'$nests'}[^}]*(?=}.*\%\%\#\#${key_title}>>)')
      open=$(echo "$chknests" | grep -o "{" | wc -l)
      close=$(echo "$chknests" | grep -o "}" | wc -l)
      [[ $open == "$close" ]] && break
      [[ $open -gt $close ]] && nests=$((nests + 1))
    done
    perl -i -e "s/(section\{|subsection\{|subsubsection\{|chapter\{|caption\{|paragraph\{)$chknests(\}.*\%\%\#\#${key_title}>>)/\1${title_value}\2/" ${file}
  done < <(echo "$keys" | grep -P ".*(?===title)")
}

function detect_abuse() {
  baseDir=$2
  compareDir=$3

  # Compare number of latex tags

  # Check URL changes
  baseFiles=$(find "$baseDir" | grep -e '\.tex$' | sed -e "s%$baseDir%%g" -e "s/^\///g")
  compareFiles=$(find "$compareDir" | grep -e '\.tex$' | sed -e "s%$compareDir%%g" -e "s/^\///g")

  while read -r test; do
    { echo "$compareFiles" | grep "$test" >/dev/null; } && {
      base=$(urlextract "$baseDir/$test")
      compare=$(urlextract "$compareDir/$test")

      echo "$compare" | grep -vh "$base"
      echo "--"
      echo " "
      echo "WARNING: $baseDir/$test(BASE) does not have these URLs, but $compareDir/$test(COMPARE) has. These links has possibility of spam!"
      echo "--"
      echo " "
    }
  done < <(echo "$baseFiles")
}

case $1 in
"update") update_xliff "$@" ;;
"merge") merge_translation "$@" ;;
"check") check_deps ;;
"checkabuse") detect_abuse "$@" ;;
esac
