/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_muntashirakon_algo_AhoCorasick */

#ifndef _Included_io_github_muntashirakon_algo_AhoCorasick
#define _Included_io_github_muntashirakon_algo_AhoCorasick
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_muntashirakon_algo_AhoCorasick
 * Method:    createNative
 * Signature: ([Ljava/lang/String;)J
 */
extern "C"
JNIEXPORT jlong JNICALL Java_io_github_muntashirakon_algo_AhoCorasick_createNative
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     io_github_muntashirakon_algo_AhoCorasick
 * Method:    searchNative
 * Signature: (JLjava/lang/String;)[I
 */
extern "C"
JNIEXPORT jintArray JNICALL Java_io_github_muntashirakon_algo_AhoCorasick_searchNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_github_muntashirakon_algo_AhoCorasick
 * Method:    searchNative
 * Signature: (J)V
 */
extern "C"
JNIEXPORT void JNICALL Java_io_github_muntashirakon_algo_AhoCorasick_destroyNative
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
