/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_muntashirakon_compat_system_OsCompat */

#ifndef _Included_io_github_muntashirakon_compat_system_OsCompat
#define _Included_io_github_muntashirakon_compat_system_OsCompat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_muntashirakon_compat_system_OsCompat
 * Method:    setgrent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_compat_system_OsCompat_setgrent
  (JNIEnv *, jclass);

/*
 * Class:     io_github_muntashirakon_compat_system_OsCompat
 * Method:    setpwent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_compat_system_OsCompat_setpwent
  (JNIEnv *, jclass);

/*
 * Class:     io_github_muntashirakon_compat_system_OsCompat
 * Method:    getgrent
 * Signature: ()Lio/github/muntashirakon/AppManager/compat/StructGroup;
 */
JNIEXPORT jobject JNICALL Java_io_github_muntashirakon_compat_system_OsCompat_getgrent
  (JNIEnv *, jclass);

/*
 * Class:     io_github_muntashirakon_compat_system_OsCompat
 * Method:    getpwent
 * Signature: ()Landroid/system/StructPasswd;
 */
JNIEXPORT jobject JNICALL Java_io_github_muntashirakon_compat_system_OsCompat_getpwent
  (JNIEnv *, jclass);

/*
 * Class:     io_github_muntashirakon_compat_system_OsCompat
 * Method:    endgrent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_compat_system_OsCompat_endgrent
  (JNIEnv *, jclass);

/*
 * Class:     io_github_muntashirakon_compat_system_OsCompat
 * Method:    endpwent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_compat_system_OsCompat_endpwent
  (JNIEnv *, jclass);

/*
 * Class:     io_github_muntashirakon_compat_system_OsCompat
 * Method:    utimensat
 * Signature: (ILjava/lang/String;Lio/github/muntashirakon/compat/system/StructTimespec;Lio/github/muntashirakon/compat/system/StructTimespec;I)V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_compat_system_OsCompat_utimensat
  (JNIEnv *, jclass, jint, jstring, jobject, jobject, jint);

/*
 * Class:     io_github_muntashirakon_compat_system_OsCompat
 * Method:    setNativeConstants
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_compat_system_OsCompat_setNativeConstants
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
