/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_muntashirakon_AppManager_utils_CpuUtils */

#ifndef _Included_io_github_muntashirakon_AppManager_utils_CpuUtils
#define _Included_io_github_muntashirakon_AppManager_utils_CpuUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_muntashirakon_AppManager_utils_CpuUtils
 * Method:    getClockTicksPerSecond
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_muntashirakon_AppManager_utils_CpuUtils_getClockTicksPerSecond
  (JNIEnv *, jclass);

/*
 * Class:     io_github_muntashirakon_AppManager_utils_CpuUtils
 * Method:    getCpuModel
 * Signature: ()java/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_muntashirakon_AppManager_utils_CpuUtils_getCpuModel
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
