/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_muntashirakon_AppManager_compat_OsCompat */

#ifndef _Included_io_github_muntashirakon_AppManager_compat_OsCompat
#define _Included_io_github_muntashirakon_AppManager_compat_OsCompat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_muntashirakon_AppManager_compat_OsCompat
 * Method:    setpwent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_AppManager_compat_OsCompat_setpwent
  (JNIEnv *, jclass);

/*
 * Class:     io_github_muntashirakon_AppManager_compat_OsCompat
 * Method:    getpwent
 * Signature: ()Landroid/system/StructPasswd;
 */
JNIEXPORT jobject JNICALL Java_io_github_muntashirakon_AppManager_compat_OsCompat_getpwent
  (JNIEnv *, jclass);

/*
 * Class:     io_github_muntashirakon_AppManager_compat_OsCompat
 * Method:    endpwent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_AppManager_compat_OsCompat_endpwent
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
